config/routes.rb
Rails.application.routes.draw do
  root to: 'catalogues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :catalogues do
  resources :voitures , only: [:new, :index, :create, :edit, :update]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalogue.rb
class Catalogue < ApplicationRecord
  has_many :voitures
end

app/models/voiture.rb
class Voiture < ApplicationRecord
  belongs_to :catalogue
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController
  def index
    @catalogues = Catalogue.all
  end

  def show
    @catalogue = Catalogue.find(params[:id])
    @voitures = Voiture.all.where(catalogue: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  def index
    @catalogue = Catalogue.find(params[:catalogue_id])
    # @voitures = Voiture.all.where(:catalogue = params(:catalogue_id))
  end

  def new
    @catalogue = Catalogue.find(params[:catalogue_id])
    @voiture = Voiture.new()
  end

  def create
    @voiture = Voiture.new(voiture_params)
  end

  private

  def voiture_params
    params.require(:voiture).permit(:nom, :code, :description, :tarif, :poids, :catalogue)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/voitures_helper.rb
module VoituresHelper
end

app/views/catalogues/index.html.erb
<h3>Liste des catalogues</h3>

<ul>
  <% @catalogues.each do |catalogue| %>
  <li><%= link_to catalogue.nom , catalogue_path(catalogue) %></li>
  <% end %>
</ul>

app/views/catalogues/show.html.erb
<h3> <%= @catalogue.nom %></h3>

<% @voitures.each do |voiture| %>
  <li><%= voiture %></li>
<% end %>

<hr>

<%= link_to "Retour à tous les catalogues" , catalogues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/voitures/index.html.erb
<h3>Liste du catalogue <%= @catalogue.nom %></h3>

<ul>
  <% @voitures.each do |voiture| %>
  <li><%= voiture.nom %></li>
  <% end %>
</ul>

<hr>

<%= link_to "Ajouter une voiture" , new_catalogue_voiture_path(@catalogue) %>

app/views/voitures/new.html.erb
<h3>New car</h3>


<div class="container">
  <div class="row">

    <div class="col-xs-6 col-xs-offset-3">
    <%= simple_form_for [@catalogue, @voiture] do |f| %>
    <%= f.input :nom %>
    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.input :tarif %>
    <%= f.input :poids %>
    <%= f.input :catalogue, :as => :hidden, :input_html => { :value => @catalogue } %>
    <%= f.submit "add a car", class: "btn btn-primary" %>
    <% end %>
    </div>

  </div>
</div>